services:
  matching-engine-integration:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_CONN=postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
      - REDIS_ADDR=redis:6379
    command: ["go", "test", "-v", "./tests/integration_test.go"]

  redis:
    image: "redis:alpine"

  postgres:
    image: "postgres:13"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql