version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # REST API
      - "8080:8080"  # gRPC
    depends_on:
      - redis
      - postgres
    environment:
      - POSTGRES_CONN=postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
      - REDIS_ADDR=redis:6379
    volumes:
      - ./:/app

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  postgres:
    image: "postgres:13"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  test:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - app
      - redis
      - postgres
    environment:
      - POSTGRES_CONN=postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
      - REDIS_ADDR=redis:6379
    volumes:
      - ./:/app
    command: ["go", "test", "./rest_test"]

volumes:
  redis-data:
  postgres-data: