// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"database/sql"
)

type Execution struct {
	ExecID       string
	ExecType     sql.NullString
	OrdStatus    sql.NullString
	ClOrdID      sql.NullString
	OrderID      sql.NullString
	Symbol       sql.NullString
	Side         sql.NullString
	OrderQty     sql.NullInt32
	Price        sql.NullFloat64
	LastQty      sql.NullInt32
	LastPx       sql.NullFloat64
	CumQty       sql.NullInt32
	LeavesQty    sql.NullInt32
	TransactTime sql.NullInt64
	OrdType      sql.NullString
}
