// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package sqlc

import (
	"context"
	"database/sql"
)

const upsertExecution = `-- name: UpsertExecution :exec
INSERT INTO executions (
    exec_type, ord_status, cl_ord_id, order_id, symbol, side, order_qty,
    price, last_qty, last_px, cum_qty, leaves_qty, exec_id, transact_time, ord_type
) VALUES (
             $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
         ) ON CONFLICT (exec_id) DO UPDATE SET
    exec_type = EXCLUDED.exec_type,
    ord_status = EXCLUDED.ord_status,
    cl_ord_id = EXCLUDED.cl_ord_id,
    order_id = EXCLUDED.order_id,
    symbol = EXCLUDED.symbol,
    side = EXCLUDED.side,
    order_qty = EXCLUDED.order_qty,
    price = EXCLUDED.price,
    last_qty = EXCLUDED.last_qty,
    last_px = EXCLUDED.last_px,
    cum_qty = EXCLUDED.cum_qty,
    leaves_qty = EXCLUDED.leaves_qty,
    transact_time = EXCLUDED.transact_time,
    ord_type = EXCLUDED.ord_type
`

type UpsertExecutionParams struct {
	ExecType     sql.NullString
	OrdStatus    sql.NullString
	ClOrdID      sql.NullString
	OrderID      sql.NullString
	Symbol       sql.NullString
	Side         sql.NullString
	OrderQty     sql.NullInt32
	Price        sql.NullFloat64
	LastQty      sql.NullInt32
	LastPx       sql.NullFloat64
	CumQty       sql.NullInt32
	LeavesQty    sql.NullInt32
	ExecID       string
	TransactTime sql.NullInt64
	OrdType      sql.NullString
}

func (q *Queries) UpsertExecution(ctx context.Context, arg UpsertExecutionParams) error {
	_, err := q.db.ExecContext(ctx, upsertExecution,
		arg.ExecType,
		arg.OrdStatus,
		arg.ClOrdID,
		arg.OrderID,
		arg.Symbol,
		arg.Side,
		arg.OrderQty,
		arg.Price,
		arg.LastQty,
		arg.LastPx,
		arg.CumQty,
		arg.LeavesQty,
		arg.ExecID,
		arg.TransactTime,
		arg.OrdType,
	)
	return err
}
