services:
  app:
    environment:
      - REDIS_ADDR=redis:6379
      - POSTGRES_ADDR=postgres:5432
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "8080:8080"
    depends_on:
      - redis
      - postgres

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  postgres:
    image: "postgres:13"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ../internal/storage/init.sql:/docker-entrypoint-initdb.d/init.sql