services:
  matching-engine-integration:
    build:
      context: ..
      dockerfile: Dockerfile
    environment:
      - POSTGRES_CONN=postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
      - REDIS_ADDR=redis:6379
    command: ["go", "test", "-v", "./tests/integration_test.go"]
    depends_on:
      - redis
      - postgres
    networks:
      - test-network

  matching-engine-unit-tests:
    build:
      context: ..
      dockerfile: Dockerfile
    environment:
      - POSTGRES_CONN=postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
      - REDIS_ADDR=redis:6379
    command: ["go", "test", "-v", "./internal/engine"]
    depends_on:
      - redis
      - postgres
    networks:
      - test-network

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - test-network

  postgres:
    image: "postgres:13"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ../internal/storage/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - test-network

networks:
  test-network:
    driver: bridge