syntax = "proto3";

package grpc;

option go_package = "grpc";

service OrderService {
  rpc PlaceNewOrder (OrderRequest) returns (OrderResponse);
  rpc SubscribeOrderUpdates (MarketRequest) returns (stream ExecReport);
}

message OrderRequest {
  string client_id = 1;
  string symbol = 2;
  string side = 3;
  float price = 4;
  int32 quantity = 5;
  string type = 6;
}

message OrderResponse {
  string order_id = 1;
  enum OrderStatus {
    PENDING = 0;
    CONFIRMED = 1;
    FAILED = 2;
  }
  OrderStatus status = 2;
}

message MarketRequest {
  string market = 1;
}

message ExecReport {
  map<string, ExecutionList> exec_report = 1;
}

message Execution {
  string execution_type = 1;
  string order_status = 2;
  string client_order_id = 3;
  string order_id = 4;
  string symbol = 5;
  string side = 6;
  int32 order_quantity = 7;
  float price = 8;
  int32 last_quantity = 9;
  float last_px = 10;
  int32 cumulative_quantity = 11;
  int32 leaves_quantity = 12;
  string execution_id = 13;
  int64 transact_time = 14;
  string order_type = 15;
}

message ExecutionList {
  repeated Execution trade = 1;
}