syntax = "proto3";

package grpc;

option go_package = "grpc";

service OrderService {
  rpc PlaceOrder (OrderRequest) returns (OrderResponse);
  rpc CancelOrder (OrderRequest) returns (OrderResponse);
  rpc SubscribeOrderUpdates (MarketRequest) returns (stream OrderResponse);
}

message OrderRequest {
  string market = 1;
  string side = 2;
  string client_id = 3;
  double price = 4;
  int32 quantity = 5;
}

message MarketRequest {
  string market = 1;
}

message Trade {
  string id = 1;
  string market = 2;
  double price = 3;
  int32 quantity = 4;
  string buy_order = 5;
  string sell_order = 6;
  int64 timestamp = 7;
}

message OrderResponse {
  string order_id = 1;
  string status = 2;
  repeated Trade trades = 3;
}